name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 배포할 브랜치 이름 (필요에 따라 변경)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # 적절한 Node.js 버전
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Fix vue-cli-service permission
      run: chmod +x ./node_modules/.bin/vue-cli-service # 실행 권한 추가

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
